# Use the Official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory content into the container at /app directory
COPY . /app

# Install any needed packages specified in the requirements.txt file
RUN pip install -r requirements.txt

# Make the port 5000 available to the world outside this container
EXPOSE 5000

# Run the app.py when the container launches
CMD [ "python", "app.py" ]